name = "InterestRates"
uuid = "09453d48-b9e1-5bf0-a018-8d5c65f8cb56"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
repo = "https://github.com/felipenoris/InterestRates.jl.git"
version = "0.3.4"

[deps]
BusinessDays = "4f18b42c-503e-5345-9536-bb0f25fc7038"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
